### ISSUE TITLE
SIGSEGV when running parallel du on large goofys directory

### ISSUE THREAD

**Issue by andrewgaul** [kahing/goofys#161]
```
$ go run du/du.go /path/to/linux-4.10/ > /dev/null
du: readdirent: software caused connection abort
du: readdirent: software caused connection abort
du: readdirent: software caused connection abort
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b4892]

goroutine 1926 [running]:
github.com/kahing/goofys/internal.(*DirHandle).ReadDir(0xc421762380, 0xc4200dedc0, 0x2, 0xc42030a6a0, 0x2, 0x2)
        /home/gaul/work/go-workspace/src/github.com/kahing/goofys/internal/handles.go:1223 +0x912
github.com/kahing/goofys/internal.(*Goofys).ReadDir(0xc4200dedc0, 0x7f396654b090, 0xc42163d860, 0xc4217348c0, 0x0, 0x0)
        /home/gaul/work/go-workspace/src/github.com/kahing/goofys/internal/goofys.go:904 +0x1ec
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc42017a200, 0xc420122240, 0x7f396654b090, 0xc42163d860, 0x7f2820, 0xc4217348c0)
        /home/gaul/work/go-workspace/src/github.com/jacobsa/fuse/fuseutil/file_system.go:164 +0xa23
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
        /home/gaul/work/go-workspace/src/github.com/jacobsa/fuse/fuseutil/file_system.go:108 +0x12a
```

**Comment by andrewgaul** [comment]
Extra logging reveals an object without a Size:

```
{
  ETag: "\"0700e5a8ffa2b7a6722f24fb16569a05\"",
  Key: "linux-4.10/arch/tile/kernel/sysfs.c",
  LastModified: 2017-03-07 10:40:38 +0000 UTC
}
```

**Comment by kahing** [comment]
does this object always not have a size?

**Comment by andrewgaul** [comment]
Different errors on different runs.  Now I encountered:

```
panic: runtime error: slice bounds out of range

goroutine 64772 [running]:
github.com/kahing/goofys/internal.(*DirHandle).ReadDir(0xc420ec0000, 0xc4200dcdc0, 0x2, 0xc42dcde220, 0x2, 0x2)
        /home/gaul/work/go-workspace/src/github.com/kahing/goofys/internal/handles.go:1216 +0xc8e
github.com/kahing/goofys/internal.(*Goofys).ReadDir(0xc4200dcdc0, 0x7f6a1a629470, 0xc42d099770, 0xc420d9e180, 0x0, 0x0)
        /home/gaul/work/go-workspace/src/github.com/kahing/goofys/internal/goofys.go:904 +0x1ec
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc4201a9100, 0xc420122540, 0x7f6a1a629470, 0xc42d099770, 0x7f3820, 0xc420d9e180)
        /home/gaul/work/go-workspace/src/github.com/jacobsa/fuse/fuseutil/file_system.go:164 +0xa23
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
        /home/gaul/work/go-workspace/src/github.com/jacobsa/fuse/fuseutil/file_system.go:108 +0x12a
```

**Comment by andrewgaul** [comment]
I also got a strange response from `ListObjects` is empty -- no `IsTruncated` field.
