### ISSUE TITLE
goofys crashed while read dir in GCS

### ISSUE THREAD

**Issue by ybalt** [kahing/goofys#247]
~$ goofys -v
goofys version 0.0.17-3d40e98b163a797e800550a30e950dc06f7229b1

2017/10/28 04:38:52.682899 fuse.DEBUG Op 0x001311e8        connection.go:396] <- OpenDir (inode 32451)
2017/10/28 04:38:52.683078 fuse.DEBUG OpenDir 32451 0xc4488933c0 []
2017/10/28 04:38:52.683101 fuse.DEBUG Jasper/Builds/Release in readdir mode
2017/10/28 04:38:52.683114 fuse.DEBUG Jasper/Builds/Release/5.17.0 in readdir mode
2017/10/28 04:38:52.683150 fuse.DEBUG Op 0x001311e8        connection.go:479] -> OK ()
2017/10/28 04:38:52.683221 fuse.DEBUG Op 0x001311e9        connection.go:396] <- ReadDir (inode 32451)
2017/10/28 04:38:52.683359 fuse.DEBUG ReadDir 32451 0xc448893940 [0]
2017/10/28 04:38:52.683383 fuse.DEBUG <-- ReadDir 32451 0xc448893b70 [. 1]
2017/10/28 04:38:52.683398 fuse.DEBUG <-- ReadDir 32451 0xc448893da0 [.. 2]
2017/10/28 04:38:52.683720 s3.DEBUG DEBUG: Request s3/ListObjects Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /images-store?delimiter=%2F&prefix=Jasper%2FBuilds%2FRelease%2F5.17.0%2F HTTP/1.1
Host: storage.googleapis.com
User-Agent: aws-sdk-go/1.8.25 (go1.8.3; linux; amd64)
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=GOOG4KJOAIU4Z5ZVLDAM/20171028/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, 
Signature=4f022d70046227970bed561cbcbf475338e083756c734263cfba0eba69eacfe1
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20171028T043852Z

-----------------------------------------------------
2017/10/28 04:38:52.683804 s3.DEBUG DEBUG: Request s3/ListObjects Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /images-store?marker=Jasper%2FBuilds%2FRelease%2F5.17.0%2F&prefix=Jasper%2FBuilds%2FRelease%2F HTTP/1.1
Host: storage.googleapis.com
User-Agent: aws-sdk-go/1.8.25 (go1.8.3; linux; amd64)
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=GOOG4KJOAIU4Z5ZVLDAM/20171028/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, 
Signature=8709185d4a549ff6c5a39ea2785e938b90a153dd55a331b7866f08cca4786848
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20171028T043852Z

-----------------------------------------------------
2017/10/28 04:38:52.734757 s3.DEBUG DEBUG: Response s3/ListObjects Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Length: 3164
Cache-Control: private, max-age=0
Content-Type: application/xml; charset=UTF-8
Date: Sat, 28 Oct 2017 04:38:52 GMT
Expires: Sat, 28 Oct 2017 04:38:52 GMT
Server: UploadServer
X-Goog-Metageneration: 1
X-Guploader-Uploadid: AEnB2UrLJ2qPLisReOjwPKVAqTlH90UaFE9ay4JMAPlF2rlzDrPpGMp_gC3zlo4SXBqvltYQcRdPIFn1QwK5Unrsj6ToAvCYUQ

-----------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8721aa]

goroutine 2887155 [running]:
github.com/kahing/goofys/internal.(*Inode).findChildUnlocked(0xc4232a8980, 0x9a50d4, 0x1, 0x1, 0x10)
        /home/khc/Code/go/src/github.com/kahing/goofys/internal/handles.go:155 +0x2a
github.com/kahing/goofys/internal.(*Goofys).insertInodeFromDirEntry(0xc4201a0340, 0xc4232a8980, 0xc44c757ab8, 0x0)
        /home/khc/Code/go/src/github.com/kahing/goofys/internal/goofys.go:719 +0xcd
github.com/kahing/goofys/internal.(*Inode).addDotAndDotDot(0xc4232a8980)
        /home/khc/Code/go/src/github.com/kahing/goofys/internal/handles.go:910 +0xf9
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc4438f4200, 0xc43fab9be6, 0x12, 0xc428f3c750, 0xc44c757e60)
        /home/khc/Code/go/src/github.com/kahing/goofys/internal/handles.go:964 +0x459
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc4201fa000, 0xc43fab9bdd, 0x1b, 0xc428f3c750, 0xc44c757e60)
        /home/khc/Code/go/src/github.com/kahing/goofys/internal/handles.go:965 +0x49b
github.com/kahing/goofys/internal.(*DirHandle).listObjectsSlurp(0xc4489717c0, 0xc42077eb40, 0x1d, 0x7f82394e7258, 0xc459835770, 0xc448971840)
        /home/khc/Code/go/src/github.com/kahing/goofys/internal/dir.go:170 +0x699
github.com/kahing/goofys/internal.(*DirHandle).listObjects.func1(0xc4489717c0, 0xc4488b2030, 0xc42ed5a600, 0xc42ed5a660)
        /home/khc/Code/go/src/github.com/kahing/goofys/internal/dir.go:229 +0x45
created by github.com/kahing/goofys/internal.(*DirHandle).listObjects
        /home/khc/Code/go/src/github.com/kahing/goofys/internal/dir.go:237 +0x615

**Comment by kahing** [comment]
What's the directory you are starting the readdir at, and what's on GCS under that subtree? Feel free to email me that info. Is it possible that you have a key such that both `key` and `key/somethingelse` exist?

**Comment by AlexFinn** [comment]
I have the same. Log: https://gist.github.com/AlexFinn/4bd2ab4961b06661bebf5d3d318af2bb
@kahing 
what additional information is required?

**Comment by kahing** [comment]
this looks like a totally different problem. Do you have reproduction steps?

**Comment by AlexFinn** [comment]
yes, and I think it's related to https://github.com/kahing/goofys/issues/253
so you can just ignore my comments here

**Comment by kahing** [comment]
https://github.com/kahing/goofys/issues/247#issuecomment-351061475 is a panic which is unrelated to #253 which is a memory leak

**Comment by AlexFinn** [comment]
aah, yes, sorry :(
no I cannot reproduce it

**Comment by EssentialMix** [comment]
We also see something like this (GCS mounted with goofys):
`goofys -v
goofys version 0.0.18-2a3ff2a2adbed07472b7902dfca348c5a21bd92b`
`
2017/12/21 21:53:06.888086 s3.DEBUG DEBUG: Request s3/GetObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /store/test-file.tgz HTTP/1.1
Host: storage.googleapis.com
User-Agent: aws-sdk-go/1.8.25 (go1.8.3; linux; amd64)
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=mys3cred/20171221/us-east-1/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=fa61b44e6c483f517d314e1e80167cab19d30e2c3939b000d93a4418e2b9c5ca
Range: bytes=21037056-42008575
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20171221T215306Z


-----------------------------------------------------
2017/12/21 21:53:06.891363 fuse.DEBUG readahead 1490 test-file.tgz [62980096 1246859 41943040]
2017/12/21 21:53:06.891562 main.DEBUG amount of available memory: 55707
2017/12/21 21:53:06.891906 main.DEBUG amount of allocated memory: 486 416
2017/12/21 21:53:06.891919 main.DEBUG using up to 5619 5MB buffers, now is 8
2017/12/21 21:53:06.892202 s3.DEBUG DEBUG: Request s3/GetObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /store/test-file.tgz HTTP/1.1
Host: storage.googleapis.com
User-Agent: aws-sdk-go/1.8.25 (go1.8.3; linux; amd64)
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=mys3cred/20171221/us-east-1/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=21b73df9b2f166b586c28dd61dbac1200503056cc53bb4bf6a4408917554fd16
Range: bytes=42008576-62980095
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20171221T215306Z


-----------------------------------------------------
2017/12/21 21:53:06.893578 s3.DEBUG DEBUG: Request s3/GetObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /store/test-file.tgz HTTP/1.1
Host: storage.googleapis.com
User-Agent: aws-sdk-go/1.8.25 (go1.8.3; linux; amd64)
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=mys3cred/20171221/us-east-1/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=71ab12bb1983911ae6e8ab0f421a1130f7b5ac274d1adacf816c9f70515d6cd0
Range: bytes=62980096-64226954
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20171221T215306Z


-----------------------------------------------------
2017/12/21 21:53:06.910266 s3.DEBUG DEBUG: Response s3/GetObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Content-Length: 213
Cache-Control: private, max-age=0
Content-Type: application/xml; charset=UTF-8
Date: Thu, 21 Dec 2017 21:53:06 GMT
Expires: Thu, 21 Dec 2017 21:53:06 GMT
Server: UploadServer
X-Guploader-Uploadid: AEnB2Uotxw_i9yhgAp4uHUdsRGql2ZHRmdwPQFEqfAvXmpQqe2RFDdROdBPzyiHBUb3c9y5ApRsZIusvUpUw6umEF9WgGOvO2lkl3uU5SWheaMu1MpNdOv8


-----------------------------------------------------
2017/12/21 21:53:06.910303 s3.DEBUG DEBUG: Validate Response s3/GetObject failed, not retrying, error InvalidAuthentication: The provided authentication header is invalid.
	status code: 400, request id: , host id: 
2017/12/21 21:53:06.910354 fuse.DEBUG < readFile 1490 test-file.tgz [0 <nil>]
2017/12/21 21:53:06.910373 fuse.DEBUG < ReadFile 1490 test-file.tgz [0 <nil>]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x85d42b]

goroutine 7239 [running]:
github.com/kahing/goofys/internal.(*Buffer).readFromStream(0xc4233a8740, 0xc4219fe018, 0x20000, 0x20000, 0x0, 0x0, 0xc420014100)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/buffer_pool.go:360 +0xcb
github.com/kahing/goofys/internal.(*Buffer).Read(0xc4233a8740, 0xc4219fe018, 0x20000, 0x20000, 0x0, 0xc57020, 0xc420014100)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/buffer_pool.go:392 +0x426
io.ReadAtLeast(0xc570e0, 0xc4233a8740, 0xc4219fe018, 0x20000, 0x20000, 0x20000, 0x0, 0xc421940400, 0x9c4318)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0xc570e0, 0xc4233a8740, 0xc4219fe018, 0x20000, 0x20000, 0x440b60, 0xc420e10740, 0xc4233b1220)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/kahing/goofys/internal.(*S3ReadBuffer).Read(0xc423222cc0, 0x1410000, 0xc4219fe018, 0x20000, 0x20000, 0x3c10000, 0x2, 0xc42326de00)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/file.go:304 +0x8c
github.com/kahing/goofys/internal.(*FileHandle).readFromReadAhead(0xc425a6f790, 0x1410000, 0xc4219fe018, 0x20000, 0x20000, 0x0, 0xc42326de88, 0x42966e)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/file.go:328 +0xa2
github.com/kahing/goofys/internal.(*FileHandle).readFile(0xc425a6f790, 0x1410000, 0xc4219fe018, 0x20000, 0x20000, 0x0, 0x0, 0x0)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/file.go:483 +0x334
github.com/kahing/goofys/internal.(*FileHandle).ReadFile(0xc425a6f790, 0x1410000, 0xc4219fe018, 0x20000, 0x20000, 0x0, 0x0, 0x0)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/file.go:415 +0x256
github.com/kahing/goofys/internal.(*Goofys).ReadFile(0xc4201a25b0, 0x7f105a410c70, 0xc422b2eff0, 0xc4210aba40, 0xc42000e3a0, 0x0)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/goofys.go:890 +0xc5
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc4202c2660, 0xc420360300, 0x7f105a410c70, 0xc422b2eff0, 0x8c6da0, 0xc4210aba40)
	/home/khc/Code/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:187 +0xadc
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
	/home/khc/Code/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:121 +0x180
`

**Comment by EssentialMix** [comment]
Sometime our instance crashing every 2-10 minutes.
`
2017/12/22 00:05:26.656673 fuse.DEBUG ReadFile 23 0xc42045a0d0 [41484288 131072]
2017/12/22 00:05:26.656746 fuse.DEBUG < readFile 23 0xc42045a310 [131072 <nil>]
2017/12/22 00:05:26.656762 fuse.DEBUG < ReadFile 23 0xc42045a560 [131072 <nil>]
2017/12/22 00:05:26.656798 fuse.DEBUG Op 0x00000bbb        connection.go:479] -> OK ()
2017/12/22 00:05:26.657082 fuse.DEBUG Op 0x00000bbc        connection.go:396] <- ReadFile (inode 23, handle 17, offset 41615360, 131072 bytes)
2017/12/22 00:05:26.657203 fuse.DEBUG ReadFile 23 0xc4203d1740 [41615360 131072]
2017/12/22 00:05:26.657294 fuse.DEBUG < readFile 23 0xc4203d1970 [131072 <nil>]
2017/12/22 00:05:26.657312 fuse.DEBUG < ReadFile 23 0xc4203d1ba0 [131072 <nil>]
2017/12/22 00:05:26.657343 fuse.DEBUG Op 0x00000bbc        connection.go:479] -> OK ()
2017/12/22 00:05:26.657627 fuse.DEBUG Op 0x00000bbd        connection.go:396] <- ReadFile (inode 23, handle 17, offset 41746432, 131072 bytes)
2017/12/22 00:05:26.657775 fuse.DEBUG ReadFile 23 0xc4203b3b80 [41746432 131072]
2017/12/22 00:05:26.657845 fuse.DEBUG < readFile 23 0xc4203b3da0 [131072 <nil>]
2017/12/22 00:05:26.657861 fuse.DEBUG < ReadFile 23 0xc4203b3f90 [131072 <nil>]
2017/12/22 00:05:26.657884 fuse.DEBUG Op 0x00000bbd        connection.go:479] -> OK ()
2017/12/22 00:05:26.658167 fuse.DEBUG Op 0x00000bbe        connection.go:396] <- ReadFile (inode 23, handle 17, offset 41877504, 131072 bytes)
2017/12/22 00:05:26.658279 fuse.DEBUG ReadFile 23 0xc42045a920 [41877504 131072]
2017/12/22 00:05:26.658350 fuse.DEBUG < readFile 23 0xc42045ab20 [131072 <nil>]
2017/12/22 00:05:26.658366 fuse.DEBUG < ReadFile 23 0xc42045ad30 [131072 <nil>]
2017/12/22 00:05:26.658389 fuse.DEBUG Op 0x00000bbe        connection.go:479] -> OK ()
2017/12/22 00:05:26.658681 fuse.DEBUG Op 0x00000bbf        connection.go:396] <- ReadFile (inode 23, handle 17, offset 42008576, 131072 bytes)
2017/12/22 00:05:26.658813 fuse.DEBUG ReadFile 23 0xc42045b2d0 [42008576 131072]
2017/12/22 00:05:26.658892 fuse.DEBUG < readFile 23 0xc42045b4f0 [0 <nil>]
2017/12/22 00:05:26.658910 fuse.DEBUG < ReadFile 23 0xc42045b6f0 [0 <nil>]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x85d3db]

goroutine 4586 [running]:
github.com/kahing/goofys/internal.(*Buffer).readFromStream(0xc420418f00, 0xc4206f8018, 0x20000, 0x20000, 0x0, 0x0, 0xc420014100)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/buffer_pool.go:360 +0xcb
github.com/kahing/goofys/internal.(*Buffer).Read(0xc420418f00, 0xc4206f8018, 0x20000, 0x20000, 0x0, 0xc53020, 0xc420014100)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/buffer_pool.go:388 +0x401
io.ReadAtLeast(0xc53120, 0xc420418f00, 0xc4206f8018, 0x20000, 0x20000, 0x20000, 0x0, 0xc4204276c0, 0xc42022c000)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0xc53120, 0xc420418f00, 0xc4206f8018, 0x20000, 0x20000, 0xc423d5fd50, 0x851366, 0xc42019c5b0)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/kahing/goofys/internal.(*S3ReadBuffer).Read(0xc4204299a0, 0x2810000, 0xc4206f8018, 0x20000, 0x20000, 0x3d29bb8, 0xc423d5fe20, 0x18)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/file.go:304 +0x8c
github.com/kahing/goofys/internal.(*FileHandle).readFromReadAhead(0xc4213f2c30, 0x2810000, 0xc4206f8018, 0x20000, 0x20000, 0x2, 0xc423d5fe88, 0x42966e)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/file.go:328 +0xa2
github.com/kahing/goofys/internal.(*FileHandle).readFile(0xc4213f2c30, 0x2810000, 0xc4206f8018, 0x20000, 0x20000, 0x0, 0x0, 0x0)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/file.go:483 +0x334
github.com/kahing/goofys/internal.(*FileHandle).ReadFile(0xc4213f2c30, 0x2810000, 0xc4206f8018, 0x20000, 0x20000, 0x0, 0x0, 0x0)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/file.go:415 +0x256
github.com/kahing/goofys/internal.(*Goofys).ReadFile(0xc42019e410, 0x7fe514d980c8, 0xc42036c330, 0xc420206b00, 0x0, 0x0)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/goofys.go:874 +0xc5
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc420111f00, 0xc420122a80, 0x7fe514d980c8, 0xc42036c330, 0x8c4b00, 0xc420206b00)
	/home/khc/Code/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:177 +0xadc
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
	/home/khc/Code/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:112 +0x12a
`

**Comment by kahing** [comment]
https://github.com/kahing/goofys/issues/247#issuecomment-353491278 is a crash during ReadFile and is a separate problem, could you file a new issue?

**Comment by silenceli** [comment]
I meet the same issue.

Please see:
https://github.com/kahing/goofys/issues/345
