### ISSUE TITLE
panic: Unknown inode

### ISSUE THREAD

**Issue by AlexFinn** [kahing/goofys#265]
```
$ goofys --version
goofys version 0.19.0-943e017724ea820eb4185419ef3c41d6f921a324
```

Log: https://gist.github.com/AlexFinn/b7fa3c49dd7a4cdadc209fbd57f0ca49
```
Jan 21 00:17:02 pl-active-j4xz goofys[12023]: panic: Unknown inode: 111625
Jan 21 00:17:02 pl-active-j4xz goofys[12023]: goroutine 16934493 [running]:
Jan 21 00:17:02 pl-active-j4xz goofys[12023]: github.com/kahing/goofys/internal.(*Goofys).getInodeOrDie(0xc420148a90, 0x1b409, 0xc423194340)
Jan 21 00:17:02 pl-active-j4xz goofys[12023]: #011/home/khc/Code/go/src/github.com/kahing/goofys/internal/goofys.go:423 +0x130
Jan 21 00:17:02 pl-active-j4xz goofys[12023]: github.com/kahing/goofys/internal.(*Goofys).OpenFile(0xc420148a90, 0xc89020, 0xc420ab8360, 0xc42667e8e0, 0x0, 0x0)
Jan 21 00:17:02 pl-active-j4xz goofys[12023]: #011/home/khc/Code/go/src/github.com/kahing/goofys/internal/goofys.go:869 +0x6a
Jan 21 00:17:02 pl-active-j4xz goofys[12023]: github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc4203a03a0, 0xc42015a480, 0xc89020, 0xc420ab8360, 0x8ba600, 0xc42667e8e0)
Jan 21 00:17:02 pl-active-j4xz goofys[12023]: #011/home/khc/Code/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:184 +0x9f1
Jan 21 00:17:02 pl-active-j4xz goofys[12023]: created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
Jan 21 00:17:02 pl-active-j4xz goofys[12023]: #011/home/khc/Code/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:121 +0x176
```

Ready to provide any additional information.
But I do not know how to reproduce separately.

**Comment by kahing** [comment]
Unfortunately the log doesn't say much. What kind of IO pattern were you doing when this happened?

**Comment by AlexFinn** [comment]
Only read. We read many files, every file is ~from 19 to 25 MB. 
total is approximately from 7 to 25 GB in one folder

**Comment by kahing** [comment]
updated your original report to inline the log since it's not that long

**Comment by coderade** [comment]
I am using the goofys in my server, and unfortunately it stopped to working and I really can't find why with the last lines on my log.
But I'm getting the a similar **panic** issue:
 
**My log last lines:**

```
2018/03/17 19:54:16.385972 s3.DEBUG DEBUG: Validate Response s3/HeadObject failed, not retrying, error NotFound: Not Found
	status code: 404, request id: A7900E71CA17001F, host id: bzusS1l9axiz90VYDlYyiM66vizMZ9YZdT78SyZqUUEeulGQz++L08+SxMpaPHgkokmxN92DYns=
2018/03/17 19:54:16.385979 s3.DEBUG HEAD 2018/.message/ = no such file or directory
2018/03/17 19:54:16.385986 fuse.DEBUG <-- LookUpInode 66744 .message no such file or directory
2018/03/17 19:54:16.386010 fuse.DEBUG Op 0x00008094        connection.go:480] -> Error: "no such file or directory"
2018/03/17 19:54:16.938873 fuse.DEBUG Op 0x00008095        connection.go:395] <- OpenDir (inode 66744)
2018/03/17 19:54:16.939177 fuse.DEBUG OpenDir 66744 2018 []
panic: 2018 is not under 

goroutine 120435 [running]:
github.com/kahing/goofys/internal.(*Inode).OpenDir(0xc424737950, 0x0)
	/home/ubuntu/go/src/github.com/kahing/goofys/internal/dir.go:104 +0x70a
github.com/kahing/goofys/internal.(*Goofys).OpenDir(0xc4201b0000, 0x9ff860, 0xc421a828d0, 0xc4202ead40, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/kahing/goofys/internal/goofys.go:726 +0x9d
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc4206ac9c0, 0xc42015a9c0, 0x9ff860, 0xc421a828d0, 0x896080, 0xc4202ead40)
	/home/ubuntu/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:178 +0xba5
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
	/home/ubuntu/go/src/github.com/jacobsa/fuse/fuseutil/file_system.go:121 +0x176
```
May you know what can be killing my goofys server by this lines?

goofys version 0.19.0
