### ISSUE TITLE
panic when running git-status in two terminals

### ISSUE THREAD

**Issue by ucirello** [kahing/goofys#341]
I am experimenting with the idea of using S3 vfs as a working area. I decided to not use catfs for caching because it is not stable yet.

I mounted with:
```sh
goofys -f --debug_fuse --debug_s3 --cheap bucket-name $HOME/src-vfs/
```

In two different terminals, I ran `git status`. It suddenly failed with a panic.

<details>
<summary>That's the errors I got in the logs.</summary>

```
-----------------------------------------------------
2018/07/14 02:09:29.381820 s3.DEBUG {
  Delimiter: "/",
  IsTruncated: false,
  Marker: "",
  MaxKeys: 1,
  Name: "cirello-bucket",
  Prefix: "src/repo/src/cirello.io/.git/index.lock/"
}
2018/07/14 02:09:29.381860 fuse.DEBUG <-- LookUpInode 214 index.lock no such file or directory
2018/07/14 02:09:29.381954 fuse.DEBUG Op 0x00000003        connection.go:481] -> Error: "no such file or directory"
2018/07/14 02:09:29.382072 fuse.DEBUG Op 0x00000007        connection.go:396] <- GetInodeAttributes (inode 214)
2018/07/14 02:09:29.382149 fuse.DEBUG GetAttributes 214 src/repo/src/cirello.io/.git []
2018/07/14 02:09:29.382213 fuse.DEBUG Op 0x00000007        connection.go:479] -> OK ()
2018/07/14 02:09:29.382281 fuse.DEBUG Op 0x00000002        connection.go:396] <- CreateFile (parent 214, name "index.lock")
2018/07/14 02:09:29.382354 fuse.DEBUG Create 214 src/repo/src/cirello.io/.git [index.lock]
2018/07/14 02:09:29.382389 fuse.DEBUG <-- CreateFile 2047 src/repo/src/cirello.io/.git/index.lock []
2018/07/14 02:09:29.382415 fuse.DEBUG Op 0x00000002        connection.go:479] -> OK (inode 2047)
2018/07/14 02:09:29.382504 fuse.DEBUG Op 0x00000006        connection.go:396] <- GetInodeAttributes (inode 214)
2018/07/14 02:09:29.382548 fuse.DEBUG GetAttributes 214 src/repo/src/cirello.io/.git []
2018/07/14 02:09:29.382572 fuse.DEBUG Op 0x00000006        connection.go:479] -> OK ()
2018/07/14 02:09:29.382621 fuse.DEBUG Op 0x00000005        connection.go:396] <- CreateFile (parent 214, name "index.lock")
2018/07/14 02:09:29.382681 fuse.DEBUG Create 214 src/repo/src/cirello.io/.git [index.lock]
2018/07/14 02:09:29.382692 fuse.DEBUG Op 0x00000004        connection.go:396] <- LookUpInode (parent 46, name ".git")
2018/07/14 02:09:29.382741 fuse.DEBUG Ref 214 src/repo/src/cirello.io/.git [80]
panic: double insert of src/repo/src/cirello.io/.git/index.lock

goroutine 103583 [running]:
github.com/kahing/goofys/internal.(*Inode).insertChildUnlocked(0xc4201447e0, 0xc421abacf0)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/handles.go:246 +0x616
github.com/kahing/goofys/internal.(*Goofys).insertInode(0xc420143e10, 0xc4201447e0, 0xc421abacf0)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/goofys.go:687 +0x53
github.com/kahing/goofys/internal.(*Goofys).CreateFile(0xc420143e10, 0x4891140, 0xc421ae7bf0, 0xc4201e6000, 0x0, 0x0)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/goofys.go:973 +0x138
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc420270720, 0xc42007ed00, 0x4891140, 0xc421ae7bf0, 0x44bcd60, 0xc4201e6000)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/jacobsa/fuse/fuseutil/file_system.go:161 +0x547
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/jacobsa/fuse/fuseutil/file_system.go:122 +0x176
```
</details>

**Comment by kahing** [comment]
What version is this?

**Comment by ucirello** [comment]
I guess `goofys-20180109-35985-h1zbtw`

**Comment by kahing** [comment]
probably fixed in latest master
