### ISSUE TITLE
goofys crash after exec du -h .

### ISSUE THREAD

**Issue by silenceli** [kahing/goofys#345]
# ENV:
- build goofys from commit id: bb740f10dcac02ddb3a859c4b7c3d9d22849af5a
- Ubuntu 16.04

# How I use goofys
- mount s3: `goofys --debug_fuse --debug_s3 -f --endpoint ${S3FS_SERVER}:${S3FS_PORT} ${S3FS_BUCKET} /media/s3fs/`
- get the size of dir: `du -h /media/s3fs/...`

# error log

```
2018/07/31 12:05:19.806827 s3.DEBUG DEBUG: Request s3/ListObjects Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /testbucket?marker=jarvis%2Fzhikangyi_sx%2F&prefix=jarvis%2F HTTP/1.1
Host: XXXXXXXXXXXXXX
User-Agent: aws-sdk-go/1.8.25 (go1.9.2; linux; amd64)
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=DKW620ONS0LNQDGA99CG/20180731/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=46197cb41fb05d3e30a2bdecca3ec724ddfda74664b16bd854dd0ab9b570000a
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180731T040519Z


-----------------------------------------------------
2018/07/31 12:05:19.807281 s3.DEBUG DEBUG: Request s3/ListObjects Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /testbucket?delimiter=%2F&prefix=jarvis%2Fzhikangyi_sx%2F HTTP/1.1
Host: XXXXXXXXXXXXXX
User-Agent: aws-sdk-go/1.8.25 (go1.9.2; linux; amd64)
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=DKW620ONS0LNQDGA99CG/20180731/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=2607245f1f256558cf5efff5e80f203dd08557b3c7a1ab675929cd24e9a3092d
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180731T040519Z


-----------------------------------------------------
2018/07/31 12:05:19.826072 s3.DEBUG DEBUG: Response s3/ListObjects Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Connection: keep-alive
Content-Type: application/xml
Date: Tue, 31 Jul 2018 04:05:21 GMT
Server: nginx/1.4.4
Vary: Accept-Encoding
X-Amz-Request-Id: tx000000000000002bd9b42-005b5fe001-12b1-default


-----------------------------------------------------
2018/07/31 12:05:20.136205 s3.DEBUG DEBUG: Response s3/ListObjects Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Connection: keep-alive
Content-Type: application/xml
Date: Tue, 31 Jul 2018 04:05:21 GMT
Server: nginx/1.4.4
Vary: Accept-Encoding
X-Amz-Request-Id: tx000000000000002bed103-005b5fe001-12b7-default


-----------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x86349a]

goroutine 9078610 [running]:
github.com/kahing/goofys/internal.(*Inode).findChildUnlocked(0xc430e20480, 0x9a0334, 0x1, 0xc42c017701, 0x12019fb00)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/handles.go:167 +0x2a
github.com/kahing/goofys/internal.(*Goofys).insertInodeFromDirEntry(0xc420139040, 0xc430e20480, 0xc42c017860, 0x0)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/goofys.go:744 +0xb5
github.com/kahing/goofys/internal.(*Inode).addDotAndDotDot(0xc430e20480)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/handles.go:954 +0xfb
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc430e202d0, 0xc44e8dafbc, 0x4, 0xc46b887e30, 0xc42c017e68)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/handles.go:996 +0x34b
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc422737200, 0xc44e8dafbc, 0x4d, 0xc46b887e30, 0xc42c017e68)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/handles.go:1013 +0x48d
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc4547a1830, 0xc44e8daf73, 0x5e, 0xc46b887e30, 0xc42c017e68)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/handles.go:1013 +0x48d
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc420b88870, 0xc44e8daf62, 0x69, 0xc46b887e30, 0xc42c017e68)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/handles.go:1013 +0x48d
github.com/kahing/goofys/internal.(*DirHandle).listObjectsSlurp(0xc43bb13340, 0xc46afd23e0, 0x14, 0xc89020, 0xc463cac4b0, 0xc43bb13380)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/dir.go:170 +0x301
github.com/kahing/goofys/internal.(*DirHandle).listObjects.func1(0xc43bb13340, 0xc44eb6f4a0, 0xc4256e2000, 0xc4256e2060)
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/dir.go:229 +0x45
created by github.com/kahing/goofys/internal.(*DirHandle).listObjects
	/home/khc/Code/go/src/github.com/kahing/goofys/internal/dir.go:228 +0x6b4
```

**Comment by silenceli** [comment]
If you need more info, please contact me.

Thank you for your reply.

**Comment by kahing** [comment]
I think this is fixed in latest master
