### ISSUE TITLE
Null pointer exception while listing directory

### ISSUE THREAD

**Issue by nqbao** [kahing/goofys#362]
It just crashes on me, and i have no idea why ...

```
goofys -v
goofys version 0.19.0-943e017724ea820eb4185419ef3c41d6f921a324
```

```
goroutine 3363 [running]:
github.com/kahing/goofys/internal.(*Inode).findChildUnlocked(0xc420530bd0, 0x45a4594, 0x1, 0x1, 0xc420dd8a80)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/handles.go:167 +0x2a
github.com/kahing/goofys/internal.(*Goofys).insertInodeFromDirEntry(0xc420165ba0, 0xc420530bd0, 0xc420abb738, 0x0)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/goofys.go:744 +0xb5
github.com/kahing/goofys/internal.(*Inode).addDotAndDotDot(0xc420530bd0)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/handles.go:954 +0xfb
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc420530900, 0xc42053234a, 0x26, 0xc420ce0390, 0xc420abbe68)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/handles.go:1012 +0x44e
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc420530510, 0xc420532339, 0x2d, 0xc420ce0390, 0xc420abbe68)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/handles.go:1013 +0x48d
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc4202b97a0, 0xc420532332, 0x33, 0xc420ce0390, 0xc420abbe68)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/handles.go:1013 +0x48d
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc4204567e0, 0xc42053232c, 0x39, 0xc420ce0390, 0xc420abbe68)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/handles.go:1013 +0x48d
github.com/kahing/goofys/internal.(*Inode).insertSubTree(0xc4205302d0, 0xc420532326, 0x41, 0xc420ce0390, 0xc420abbe68)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/handles.go:1013 +0x48d
github.com/kahing/goofys/internal.(*DirHandle).listObjectsSlurp(0xc420228380, 0xc420d8c840, 0x23, 0x4891140, 0xc420f048d0, 0x0)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/dir.go:170 +0x301
github.com/kahing/goofys/internal.(*DirHandle).listObjects.func1(0xc420228380, 0xc42044ab20, 0xc420c201e0, 0xc420c20240)
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/dir.go:229 +0x45
created by github.com/kahing/goofys/internal.(*DirHandle).listObjects
	/private/tmp/goofys-20180109-35985-h1zbtw/gopath/src/github.com/kahing/goofys/internal/dir.go:228 +0x6b4
```

**Comment by kahing** [comment]
fixed in master
