### ISSUE TITLE
ForgetInode race condition lead to "panic: Unknown inode"?

### ISSUE THREAD

**Issue by zhjunqin** [kahing/goofys#392]
I met following issue when use goofys.

```
2019/01/07 20:55:18.486805 fuse.DEBUG Op 0x0002b709        connection.go:395] <- LookUpInode (parent 4, name "record-00066-of-00100")
2019/01/07 20:55:18.487230 fuse.DEBUG Inode.LookUp 4 record/files [record-00066-of-00100]
2019/01/07 20:55:18.493826 fuse.DEBUG <-- LookUpInode 4 coco_train.record-00066-of-00100 <nil>
2019/01/07 20:55:18.494513 fuse.DEBUG Op 0x0002b709        connection.go:478] -> OK (inode 1985)
2019/01/07 20:55:18.494815 fuse.DEBUG Op 0x0002b70a        connection.go:395] <- LookUpInode (parent 4, name "record-00066-of-00100")
2019/01/07 20:55:18.494916 fuse.DEBUG Op 0x0002b70b        connection.go:395] <- ForgetInode (inode 1985)
2019/01/07 20:55:18.494999 fuse.DEBUG DeRef 1985 record/files/record-00066-of-00100 [1 1]
2019/01/07 20:55:18.495071 fuse.DEBUG Ref 1985 record/files/record-00066-of-00100 [0]
2019/01/07 20:55:18.495098 fuse.DEBUG <-- LookUpInode 4 record-00066-of-00100 <nil>
2019/01/07 20:55:18.495134 fuse.DEBUG Op 0x0002b70a        connection.go:478] -> OK (inode 1985)
2019/01/07 20:55:18.495230 fuse.DEBUG Op 0x0002b70b        connection.go:478] -> OK ()
2019/01/07 20:55:18.495271 fuse.DEBUG Op 0x0002b70c        connection.go:395] <- OpenFile (inode 1985)
panic: Unknown inode: 1985

goroutine 243042 [running]:
github.com/kahing/goofys/internal.(*Goofys).getInodeOrDie(0xc420242340, 0x7c1, 0xc4204dbf60)
        /opt/bin/goofys/work/src/github.com/kahing/goofys/internal/goofys.go:421 +0x126
github.com/kahing/goofys/internal.(*Goofys).OpenFile(0xc420242340, 0xa01b20, 0xc429697a70, 0xc42915c860, 0x0, 0x0)
        /opt/bin/goofys/work/src/github.com/kahing/goofys/internal/goofys.go:870 +0x60
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc42000c7a0, 0xc4202fcdd0, 0xa01b20, 0xc429697a70, 0x8992c0, 0xc42915c860)
        /opt/bin/goofys/work/src/github.com/jacobsa/fuse/fuseutil/file_system.go:187 +0xab8
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
        /opt/bin/goofys/work/src/github.com/jacobsa/fuse/fuseutil/file_system.go:121 +0x176
```

I checked code in `ForgetInode`, there is no fs lock in `removeChild`.

It seems `ForgetInode` remove the inode, then `LookUpInode` read it again.

```
	if stale {
		delete(fs.inodes, op.Inode)
		fs.forgotCnt += 1
		fs.mu.Unlock()

		if inode.Parent != nil {
			inode.Parent.removeChild(inode)
		}
	} else {
		fs.mu.Unlock()
	}
```

**Comment by zhjunqin** [comment]
I added some debug log confirmed that 

1.  `ForgetInode ` get `fs.mu.Lock()`
2. `LookUpInode` get `parent.mu.Lock()`
3. `ForgetInode ` release `fs.mu.Unlock()` and wait for `parent.mu.Lock()` in `inode.Parent.removeChild(inode)`
4. `LookUpInode` get `fs.mu.Lock()` then get inode
5. `LookUpInode` release `parent.mu.Unlock()`
6. `inode.Parent.removeChild(inode)` get `parent.mu.Lock()` and remove the inode

I think  `ForgetInode ` should not release `fs.mu.Unlock()` before `inode.Parent.removeChild(inode)`, what do you think?

And I really want to know how `ForgetInode` is trggered and why `ForgetInode` is called so frequently?

Thanks you very much!
