### ISSUE TITLE
Can only run in foreground

### ISSUE THREAD

**Issue by bcli4d** [kahing/goofys#440]
I'm using goofys in a docker container (Ubuntu 14.04). When running as root, I can successfully mount a bucket to a directory owned by root. 

I'm running apache2 in the container, and it seems that the directory to which the bucket is mounted needs to be owned by www-data; www-data is  the user that apache2 configures by default. For this purpose, I first change the directory owner and group to www-data. Then, as www-data, run goofys. If I do not include the -f flag, the mount fails:

```
www-data@70d2858b20d1:/root/src$ ./goofys --profile google --endpoint https://storage.googleapis.com gdc-tcga-phs000178-open /data/images/gdc-tcga-phs000178-open
panic: unable to daemonize: fork/exec /root/src/goofys: permission denied

goroutine 1 [running]:
main.main.func1(0xc0000c2580, 0xb223e0, 0xc00011ff80)
	/home/khc/Code/go/src/github.com/kahing/goofys/main.go:186 +0x934
github.com/urfave/cli.HandleAction(0x96e960, 0xc00000ecc0, 0xc0000c2580, 0x0, 0x0)
	/home/khc/Code/go/src/github.com/urfave/cli/app.go:502 +0xbe
github.com/urfave/cli.(*App).Run(0xc000178000, 0xc000020070, 0x7, 0x7, 0x0, 0x0)
	/home/khc/Code/go/src/github.com/urfave/cli/app.go:268 +0x5aa
main.main()
	/home/khc/Code/go/src/github.com/kahing/goofys/main.go:246 +0x14e
```
However, adding the -f flag allows the mount to succeed:

```
www-data@70d2858b20d1:/root/src$ ./goofys -f --profile google --endpoint https://storage.googleapis.com gdc-tcga-phs000178-open /data/images/gdc-tcga-phs000178-open
2019/07/24 21:41:14.365860 main.INFO File system has been successfully mounted.
```

I'd prefer to _not_ keep goofys in the foreground. Any suggestions how to do that? 

Thanks.

**Comment by kahing** [comment]
how are you running this container?

**Comment by bcli4d** [comment]
Just using a standard docker run command. I'm guessing there is something else that you are trying to get at?

Actually, in retrospect, leaving it in the foreground seems to be working fine. But maybe the problem itself might be of interest to you.

Thanks.

**Comment by bcli4d** [comment]
By the way, I switched from gcsfuse to goofys because I need to access a Google bucket which does not have implicit directories, and the  gcsfuse -implicit-dirs switch absolutely kills performance. Even though goofys has the corresponding implicit dirs capability enabled, performance is acceptable.

Way to go!! :-)

**Comment by kahing** [comment]
could you share some numbers?

**Comment by bcli4d** [comment]
Sorry, I do not have any numbers. The performance difference was so obvious
that benchmarking was not needed.

FYI, the application is browser based viewing of very large images (e.g.
100Kx100K pixels), and based on openseadragon
<https://openseadragon.github.io/> to enable panning and zooming. The
server is based on a file oriented library that can serve image tiles
(subregions of the image). The client requests just the tiles that it needs
to display the current zoom level and pan location, so there are lots of
random reads of the blob as the user moves around the image.
