### ISSUE TITLE
Error when using tensorflow TFRecordWriter

### ISSUE THREAD

**Issue by saswatac** [kahing/goofys#563]
I have mounted a google storage bucket using goofys and writing tfrecord files using TFRecordWriter is resulting in errors.

Tensorflow error -
```
tensorflow.python.framework.errors_impl.UnknownError: /home/container_user/data/final/tfrecord_geometry_ds/shard-0000-of-9999.tfr; Input/output error
```

goofys log -

```
main.ERROR stacktrace from panic: runtime error: invalid memory address or nil pointer dereference #012goroutine 39171 [running]:#012runtime/debug.Stack(0xc000205b28, 0xc1df20, 0x14497c0)#012#011/usr/local/go/src/runtime/debug/stack.go:24 +0x9d#012github.com/kahing/goofys/api/common.LogPanic(0xc000205f18)#012#011/home/kahing/go/src/github.com/kahing/goofys/api/common/panic_logger.go:32 +0x7c#012panic(0xc1df20, 0x14497c0)#012#011/usr/local/go/src/runtime/panic.go:679 +0x1b2#012github.com/kahing/goofys/internal.(*Inode).renameObject(0xc00035b0e0, 0xc000262000, 0xc00188fb58, 0xc000e134c0, 0x31, 0xc00009dca0, 0x16, 0xc00174aad0, 0xc)#012#011/home/kahing/go/src/github.com/kahing/goofys/internal/dir.go:1105 +0xa9#012github.com/kahing/goofys/internal.(*FileHandle).FlushFile(0xc00050a700, 0x0, 0x0)#012#011/home/kahing/go/src/github.com/kahing/goofys/internal/file.go:750 +0x30d#012github.com/kahing/goofys/internal.(*Goofys).FlushFile(0xc000262000, 0xeb0780, 0xc0018e8840, 0xc0016887e0, 0x8, 0x1474f20)#012#011/home/kahing/go/src/github.com/kahing/goofys/internal/goofys.go:916 +0xc2#012github.com/kahing/goofys/api/common.FusePanicLogger.FlushFile(0xec2120, 0xc000262000, 0xeb0780, 0xc0018e8840, 0xc0016887e0, 0x0, 0x0)#012#011/home/kahing/go/src/github.com/kahing/goofys/api/common/panic_logger.go:121 +0x9d#012github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc000486160, 0xc000214b60, 0xeb0780, 0xc0018e8840, 0xbb2700, 0xc0016887e0)#012#011/home/kahing/go/src/github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:199 +0x6b0#012created by github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps#012#011/home/kahing/go/src/github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:121 +0x1a0#012
```

I have mounted as follows -

```
goofys -o allow_other --file-mode 0777 --dir-mode 0777 --endpoint https://storage.googleapis.com $BUCKET $MOUNT_DIR;
```

```
goofys --version
goofys version 0.23.1-b720aae5b4845855bb3d06b8ade10585934cd1e2
```

**Comment by saswatac** [comment]
I do not face the issue when using the latest version 0.24.0 . resolving.
