### ISSUE TITLE
Duplicate inode created on MkDir when executed simultaneously with same name

### ISSUE THREAD

**Issue by skuppa** [kahing/goofys#571]
The goofy restarts on when same directory created simultaneously.  The stack trace from goofy is

```
panic: double insert of some_name/folders/37079

goroutine 11332 [running]: github.com/kahing/goofys/internal.(*Inode).insertChildUnlocked(0xc00026e900, 0xc000685710) /root/go/src/github.com/kahing/goofys/internal/handles.go:246 +0x4bd
github.com/kahing/goofys/internal.(*Goofys).insertInode(0xc000290c30, 0xc00026e900, 0xc000685710) /root/go/src/github.com/kahing/goofys/internal/goofys.go:687 +0x54
github.com/kahing/goofys/internal.(*Goofys).MkDir(0xc000290c30, 0xd3a200, 0xc000dbf050, 0xc000d422a0, 0x0, 0x0) /root/go/src/github.com/kahing/goofys/internal/goofys.go:1029 +0x1a7
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc000398ba0, 0xc0002905b0, 0xd3a200, 0xc000dbf050, 0xa2e7c0, 0xc000d422a0) /root/go/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20180417054321-cd3959611bcb/fuseutil/file_system.go:154 +0xb0b
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps /root/go/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20180417054321-cd3959611bcb/fuseutil/file_system.go:121 +0x173
```

**Comment by skuppa-veeva** [comment]
Here is PR to fix this issue: 

https://github.com/kahing/goofys/pull/572

**Comment by skuppa-veeva** [comment]
@kahing I created a PR to fix this issue, could you review and let me know your feedback.
