### ISSUE TITLE
Goofys panic: Unknown inode {inode_ID} in ForgetInode func

### ISSUE THREAD

**Issue by WPH95** [kahing/goofys#573]
```
INFO  [2020-10-26 12:43:54,296] echo: /usr/bin/goofys[41]: main.ERROR stacktrace from panic: Unknown inode: 118425 
goroutine 101 [running]:
runtime/debug.Stack(0xc000fb3c08, 0xbd2e60, 0xc002e87310)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/kahing/goofys/api/common.LogPanic(0xc000fb3e48)
	/home/kahing/go/src/github.com/kahing/goofys/api/common/panic_logger.go:32 +0x7c
panic(0xbd2e60, 0xc002e87310)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kahing/goofys/internal.(*Goofys).getInodeOrDie(...)
	/home/kahing/go/src/github.com/kahing/goofys/internal/goofys.go:282
github.com/kahing/goofys/internal.(*Goofys).ForgetInode(0xc00023e000, 0xeb5b00, 0xc002dd5020, 0xc001d8a000, 0x0, 0x0)
	/home/kahing/go/src/github.com/kahing/goofys/internal/goofys.go:758 +0x34b
github.com/kahing/goofys/api/common.FusePanicLogger.ForgetInode(0xec7540, 0xc00023e000, 0xeb5b00, 0xc002dd5020, 0xc001d8a000, 0x0, 0x0)
	/home/kahing/go/src/github.com/kahing/goofys/api/common/panic_logger.go:61 +0x9d
github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc00000c4e0, 0xc0001b31e0, 0xeb5b00, 0xc002dd5020, 0xbb6900, 0xc001d8a000)
	/home/kahing/go/src/github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:152 +0xa07
github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps(0xc00000c4e0, 0xc0001b31e0)
	/home/kahing/go/src/github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:120 +0x140
github.com/kahing/goofys/vendor/github.com/jacobsa/fuse.Mount.func1(0xea5560, 0xc00000c4e0, 0xc0001b31e0, 0xc000238e10)
	/home/kahing/go/src/github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/mount.go:84 +0x3f
created by github.com/kahing/goofys/vendor/github.com/jacobsa/fuse.Mount
	/home/kahing/go/src/github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/mount.go:83 +0x4fe
```

**Comment by WPH95** [comment]
debug log 
```
INFO  [2020-10-26 12:43:54,250] echo: /usr/bin/goofys[41]: fuse.DEBUG <-- LookUpInode 2 5f94e518_0 <nil>
INFO  [2020-10-26 12:43:54,250] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d81        connection.go:491] -> OK (inode 139120)
INFO  [2020-10-26 12:43:54,250] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d82        connection.go:408] <- ForgetInode (inode 139120)
INFO  [2020-10-26 12:43:54,250] echo: /usr/bin/goofys[41]: fuse.DEBUG DeRef 139120 logs/5f94e518_0 [1 1]
INFO  [2020-10-26 12:43:54,250] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d82        connection.go:491] -> OK ()
INFO  [2020-10-26 12:43:54,250] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d83        connection.go:408] <- LookUpInode (parent 2, name "5f94e518_0")
INFO  [2020-10-26 12:43:54,250] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d84        connection.go:408] <- ForgetInode (inode 118423)
INFO  [2020-10-26 12:43:54,250] echo: /usr/bin/goofys[41]: fuse.DEBUG DeRef 118423 5f94e518_0 [2 2]
INFO  [2020-10-26 12:43:54,250] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d84        connection.go:491] -> OK ()
INFO  [2020-10-26 12:43:54,251] echo: /usr/bin/goofys[41]: fuse.DEBUG Inode.LookUp 2 logs [5f94e518_0]
INFO  [2020-10-26 12:43:54,260] echo: /usr/bin/goofys[41]: fuse.DEBUG <-- LookUpInode 2 5f94e518_0 <nil>
INFO  [2020-10-26 12:43:54,260] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d83        connection.go:491] -> OK (inode 139978)
INFO  [2020-10-26 12:43:54,260] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d85        connection.go:408] <- LookUpInode (parent 2, name "5f94e51e_2")
INFO  [2020-10-26 12:43:54,260] echo: /usr/bin/goofys[41]: fuse.DEBUG Ref 139121 logs/5f94e51e_2 [0]
INFO  [2020-10-26 12:43:54,260] echo: /usr/bin/goofys[41]: fuse.DEBUG <-- LookUpInode 2 5f94e51e_2 <nil>
INFO  [2020-10-26 12:43:54,261] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d85        connection.go:491] -> OK (inode 139121)
INFO  [2020-10-26 12:43:54,261] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d86        connection.go:408] <- ForgetInode (inode 139121)
INFO  [2020-10-26 12:43:54,261] echo: /usr/bin/goofys[41]: fuse.DEBUG DeRef 139121 logs/5f94e51e_2 [1 1]
INFO  [2020-10-26 12:43:54,261] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d86        connection.go:491] -> OK ()
INFO  [2020-10-26 12:43:54,261] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d87        connection.go:408] <- LookUpInode (parent 2, name "5f94e51e_2")
INFO  [2020-10-26 12:43:54,261] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d88        connection.go:408] <- ForgetInode (inode 118424)
INFO  [2020-10-26 12:43:54,261] echo: /usr/bin/goofys[41]: fuse.DEBUG DeRef 118424 5f94e51e_2 [2 2]
INFO  [2020-10-26 12:43:54,261] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d88        connection.go:491] -> OK ()
INFO  [2020-10-26 12:43:54,261] echo: /usr/bin/goofys[41]: fuse.DEBUG Inode.LookUp 2 logs [5f94e51e_2]
INFO  [2020-10-26 12:43:54,272] echo: /usr/bin/goofys[41]: fuse.DEBUG <-- LookUpInode 2 5f94e51e_2 <nil>
INFO  [2020-10-26 12:43:54,273] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d87        connection.go:491] -> OK (inode 139979)
INFO  [2020-10-26 12:43:54,273] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d89        connection.go:408] <- LookUpInode (parent 2, name "5f94e51e_3")
INFO  [2020-10-26 12:43:54,273] echo: /usr/bin/goofys[41]: fuse.DEBUG Ref 139122 logs/5f94e51e_3 [0]
INFO  [2020-10-26 12:43:54,273] echo: /usr/bin/goofys[41]: fuse.DEBUG <-- LookUpInode 2 5f94e51e_3 <nil>
INFO  [2020-10-26 12:43:54,274] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d89        connection.go:491] -> OK (inode 139122)
INFO  [2020-10-26 12:43:54,274] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8a        connection.go:408] <- ForgetInode (inode 139122)
INFO  [2020-10-26 12:43:54,274] echo: /usr/bin/goofys[41]: fuse.DEBUG DeRef 139122 logs/5f94e51e_3 [1 1]
INFO  [2020-10-26 12:43:54,274] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8a        connection.go:491] -> OK ()
INFO  [2020-10-26 12:43:54,274] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8b        connection.go:408] <- LookUpInode (parent 2, name "5f94e51e_3")
INFO  [2020-10-26 12:43:54,274] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8c        connection.go:408] <- ForgetInode (inode 117583)
INFO  [2020-10-26 12:43:54,274] echo: /usr/bin/goofys[41]: fuse.DEBUG DeRef 117583 5f94e51e_3 [2 2]
INFO  [2020-10-26 12:43:54,275] echo: /usr/bin/goofys[41]: fuse.DEBUG Inode.LookUp 2 logs [5f94e51e_3]
INFO  [2020-10-26 12:43:54,275] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8c        connection.go:491] -> OK ()
INFO  [2020-10-26 12:43:54,283] echo: /usr/bin/goofys[41]: fuse.DEBUG <-- LookUpInode 2 5f94e51e_3 <nil>
INFO  [2020-10-26 12:43:54,284] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8b        connection.go:491] -> OK (inode 139980)
INFO  [2020-10-26 12:43:54,284] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8d        connection.go:408] <- LookUpInode (parent 2, name "5f94e526_1")
INFO  [2020-10-26 12:43:54,284] echo: /usr/bin/goofys[41]: fuse.DEBUG Ref 139123 logs/5f94e526_1 [0]
INFO  [2020-10-26 12:43:54,284] echo: /usr/bin/goofys[41]: fuse.DEBUG <-- LookUpInode 2 5f94e526_1 <nil>
INFO  [2020-10-26 12:43:54,284] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8d        connection.go:491] -> OK (inode 139123)
INFO  [2020-10-26 12:43:54,284] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8e        connection.go:408] <- ForgetInode (inode 139123)
INFO  [2020-10-26 12:43:54,284] echo: /usr/bin/goofys[41]: fuse.DEBUG DeRef 139123 logs/5f94e526_1 [1 1]
INFO  [2020-10-26 12:43:54,285] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8e        connection.go:491] -> OK ()
INFO  [2020-10-26 12:43:54,285] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8f        connection.go:408] <- LookUpInode (parent 2, name "5f94e526_1")
INFO  [2020-10-26 12:43:54,285] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d90        connection.go:408] <- ForgetInode (inode 117584)
INFO  [2020-10-26 12:43:54,285] echo: /usr/bin/goofys[41]: fuse.DEBUG DeRef 117584 5f94e526_1 [2 2]
INFO  [2020-10-26 12:43:54,285] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d90        connection.go:491] -> OK ()
INFO  [2020-10-26 12:43:54,285] echo: /usr/bin/goofys[41]: fuse.DEBUG Inode.LookUp 2 logs [5f94e526_1]
INFO  [2020-10-26 12:43:54,295] echo: /usr/bin/goofys[41]: fuse.DEBUG <-- LookUpInode 2 5f94e526_1 <nil>
INFO  [2020-10-26 12:43:54,295] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d8f        connection.go:491] -> OK (inode 139981)
INFO  [2020-10-26 12:43:54,295] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d91        connection.go:408] <- LookUpInode (parent 2, name "5f94e527_0")
INFO  [2020-10-26 12:43:54,296] echo: /usr/bin/goofys[41]: fuse.DEBUG Ref 139124 logs/5f94e527_0 [0]
INFO  [2020-10-26 12:43:54,296] echo: /usr/bin/goofys[41]: fuse.DEBUG <-- LookUpInode 2 5f94e527_0 <nil>
INFO  [2020-10-26 12:43:54,296] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d91        connection.go:491] -> OK (inode 139124)
INFO  [2020-10-26 12:43:54,296] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d92        connection.go:408] <- ForgetInode (inode 139124)
INFO  [2020-10-26 12:43:54,296] echo: /usr/bin/goofys[41]: fuse.DEBUG DeRef 139124 logs/5f94e527_0 [1 1]
INFO  [2020-10-26 12:43:54,296] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d92        connection.go:491] -> OK ()
INFO  [2020-10-26 12:43:54,296] echo: /usr/bin/goofys[41]: fuse.DEBUG Op 0x000a2d94        connection.go:408] <- ForgetInode (inode 118425)
INFO  [2020-10-26 12:43:54,296] echo: /usr/bin/goofys[41]: main.ERROR stacktrace from panic: Unknown inode: 118425 
```

debug log looks strange. guess kernel loses Op 0x000a2d93
should Lookup Inode 118425 first, btw some reason ForgetInode Op recived first. make goofys crash

**Comment by bundai223** [comment]
I have encounter the same issue.

**Comment by stevyn81** [comment]
Hello, we are also encountering this.
