### ISSUE TITLE
Detect transport endpoint disconnection

### ISSUE THREAD

**Issue by zheliazkov** [kahing/goofys#610]
Hello,

I'm testing goofys with a seaweedfs object storage & filer.
While trying to copy a lot of files the goofys crashes.

Running it with strace it says that there is null pointer exception at https://github.com/kahing/goofys/blob/45b8d78375af1b24604439d2e60c567654bcdf88/internal/backend_s3.go#L373 .

Does somebody else experienced that behavior? I'm trying to build it on my own to debug instead of using the binary but it also fails as other guys at issue #527.

`futex(0x1464860, FUTEX_WAIT_PRIVATE, 0, {tv_sec=29, tv_nsec=999833715}panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb03b5c]

goroutine 65063 [running]:
github.com/kahing/goofys/internal.(*S3Backend).HeadBlob(0xc0001d24d0, 0xc00494ed00, 0x0, 0xc001807178, 0x4)
        /home/kahing/go/src/github.com/kahing/goofys/internal/backend_s3.go:373 +0x1bc
github.com/kahing/goofys/internal.(*Inode).LookUpInodeNotDir(0xc0002e40a0, 0xc001807178, 0x4, 0xc00225ecc0, 0xc00225ed20)
        /home/kahing/go/src/github.com/kahing/goofys/internal/dir.go:1295 +0x101
created by github.com/kahing/goofys/internal.(*Inode).LookUpInodeMaybeDir
        /home/kahing/go/src/github.com/kahing/goofys/internal/dir.go:1342 +0x10b3
) = ?`

**Comment by chrislusf** [comment]
@zheliazkov Just curious, why not use SeaweedFS FUSE `weed mount` directly?

**Comment by zheliazkov** [comment]
@chrislusf I've used it already :) Thanks. 

BR,

**Comment by kahing** [comment]
that line looks like seaweed is sometimes not returning content-length?
