### ISSUE TITLE
`invalid memory address or nil pointer dereference` result in i/o error

### ISSUE THREAD

**Issue by izznogood** [kahing/goofys#644]
hello,

goofys version
```
goofys version 0.24.0-45b8d78375af1b24604439d2e60c567654bcdf88
```
We are currently using goofys in distributed mode.

our share is mounted on several servers:
fstab
```
goofys#test:/docs/data /data/docs/data fuse _netdev,allow_other,--file-mode=0666,--dir-mode=0777,--uid=1000,--gid=1000,--endpoint=https://myendpoint.lan/ 0 0
```

 and the mounts are heavily used. We currently have over 30,000 files and it's only going to get bigger.

The problem is that we regularly have this type of problem:
```
/usr/local/bin/goofys[3532]: main.ERROR stacktrace from panic: runtime error: invalid memory address or nil pointer dereference #012
goroutine 65445017 [running]:#012
runtime/debug.Stack(0xc001b25b28, 0xc224a0, 0x14517c0)#012#011

/usr/local/go/src/runtime/debug/stack. go:24 +0x9d#012
github.com/kahing/goofys/api/common.LogPanic(0xc001b25f18)#012#011

/home/kahing/go/src/github. com/kahing/goofys/api/common/panic_logger.go:32 +0x7c#012
panic(0xc224a0, 0x14517c0)#012#011

/usr/local/go/src/runtime/panic. go:679 +0x1b2#012github.com/kahing/goofys/internal.(*Inode). renameObject(0xc026c54320, 0xc00027c000, 0xc012f27740, 0xc01981d500, 0x52, 0xc0200d79c4, 0x4, 0xc0005134e0, 0xc01fed9250)#012#011

/home/kahing/go/src/github. com/kahing/goofys/internal/dir.go:1117 +0xa9#012
github.com/kahing/goofys/internal.(*FileHandle).FlushFile(0xc000279680, 0x0, 0x0)#012#011

/home/kahing/go/src/github.com/kahing/goofys/internal/file.go:799 +0x380#012github. com/kahing/goofys/internal.(*Goofys).FlushFile(0xc00027c000, 0xeb5b00, 0xc02a899770, 0xc02807c800, 0x96b07c, 0x0)#012#011

/home/kahing/go/src/github. com/kahing/goofys/internal/goofys.go:971 +0xc2#012
github.com/kahing/goofys/api/common. FusePanicLogger.FlushFile(0xec7540, 0xc00027c000, 0xeb5b00, 0xc02a899770, 0xc02807c800, 0x0, 0x0)#012#011/home/kahing/go/src/github. com/kahing/goofys/api/common/panic_logger.go:125 +0x9d#012
github.com/kahing/goofys/vendor/github. com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc000584180, 0xc0000ec270, 0xeb5b00, 0xc02a899770, 0xbb68c0, 0xc02807c800)#012#011

/home/kahing/go/src/github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil/file_system. go:200 +0x738#012
created by github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps#012#011

/home/kahing/go/src/github.com/kahing/goofys/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:122 +0x1a0
```

the errors of `invalid memory address or nil pointer dereference` result in i/o error.

Does somebody else experienced that behavior?

**Comment by stevyn81** [comment]
Hello, yes, we have these errors daily also. My fstab mount looks same as yours.

**Comment by izznogood** [comment]
hello, sorry but I don't follow this issue anymore. We stopped mounting our bucket in filesystem mode.
