### ISSUE TITLE
panic: Page size is unexpectedly 65536  goroutine 1 [running]: github.com/jacobsa/fuse/internal/buffer.init.0() 	/root/go/pkg/mod/github.com/kahing/fusego@v0.0.0-20200327063725-ca77844c7bcc/internal/buffer/in_message.go:33 +0xb8

### ISSUE THREAD

**Issue by hongjun0619** [kahing/goofys#661]
Go version: go version go1.16.4 linux/arm64
System: 4.18.0-193.28.1.el7.aarch64

Commands that were run:
# goofys version

Expected result: goofys can use normally

Result:
panic: Page size is unexpectedly 65536

goroutine 1 [running]:
github.com/jacobsa/fuse/internal/buffer.init.0()
	/root/go/pkg/mod/github.com/kahing/fusego@v0.0.0-20200327063725-ca77844c7bcc/internal/buffer/in_message.go:33 +0xb8

**Comment by gaul** [comment]
@kahing need to update FUSE to include jacobsa/fuse#102.

**Comment by hongjun0619** [comment]
@gaul @kahing
I can install goofys by this [article](https://github.com/kahing/goofys/issues/527) in Linux CentOS7 ARM(aarch64),but I can't use it normally.

Regrads.

**Comment by hongjun0619** [comment]
I want to know if goofys supports Linux ARM?

**Comment by hongjun0619** [comment]
@gaul 
We want to use AWS R6g instance, but goofys don't work, In this case, we cannot use this type. It is more urgent. When you have time to see it, I hope you can reply. If it is really not supported, we will give up using goofys, or think of other methods. If it is not possible, we have to cancel it.(Plan for this kind of instance)

Regards.
