### ISSUE TITLE
panic: Unable to connect to local syslog daemon

### ISSUE THREAD

**Issue by hierony94** [kahing/goofys#96]
Dear @kahing ,

I got this error while mounting the s3 bucket to mountpoint.
Here's the error,

```
panic: Unable to connect to local syslog daemon [recovered]
        panic: Unable to connect to local syslog daemon

goroutine 1 [running]:
panic(0x875300, 0xc820015e20)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/codegangsta/cli.HandleAction.func1(0xc820123b80)
        /root/work/src/github.com/codegangsta/cli/app.go:476 +0x417
panic(0x875300, 0xc820015e20)
        /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/kahing/goofys/internal.InitLoggers(0xc82000cd01)
        /root/work/src/github.com/kahing/goofys/internal/logger.go:42 +0xf7
main.main.func1(0xc82000cdc0, 0x0, 0x0)
        /root/work/src/github.com/kahing/goofys/main.go:166 +0x3b2
reflect.Value.call(0x88fcc0, 0xc820015930, 0x13, 0xa28df8, 0x4, 0xc820123ae0, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x88fcc0, 0xc820015930, 0x13, 0xc820123ae0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/codegangsta/cli.HandleAction(0x88fcc0, 0xc820015930, 0xc82000cdc0, 0x0, 0x0)
        /root/work/src/github.com/codegangsta/cli/app.go:485 +0x2ee
github.com/codegangsta/cli.(*App).Run(0xc820001380, 0xc82000a180, 0x3, 0x3, 0x0, 0x0)
        /root/work/src/github.com/codegangsta/cli/app.go:244 +0xb05
main.main()
        /root/work/src/github.com/kahing/goofys/main.go:217 +0x114
```

Please help me figure out what's is the culprit.
Thanks.

**Comment by kahing** [comment]
Do you have a local syslog daemon? If you don't, you can pass -f to make goofys run in foreground, which will log to the console

**Comment by hierony94** [comment]
Seems ok now.
But get this error.

```
2016/08/02 02:57:57.297868 s3.INFO Switching from region 'us-west-2' to 'ap-southeast-1'
2016/08/02 02:57:57.322642 main.FATAL Mounting file system: Mount: mount: running fusermount: exec: "fusermount": executable file not found in $PATH

stderr:
```

I'm suspect that I don't install fusermount properly.
Do you know how to install fusermount in ubuntu14.04?

Thanks.

**Comment by kahing** [comment]
install `fuse-utils` as instructed in the README

**Comment by hierony94** [comment]
I finally can mount the S3 bucket, but it should run in Foreground.
What should I do so it can be run on Background?

Thanks.

**Comment by kahing** [comment]
It runs in background if you don't use -f. But that requires syslog. 
On Aug 1, 2016 22:44, Hierony Manurung <notifications@github.com> wrote:I finally can mount the S3 bucket, but it should run in Foreground.
What should I do so it can be run on Background?

Thanks.
